### ISSUE TITLE
Shift Signature along a timeline during the execution of a test

### ISSUE THREAD

**Issue by nulltoken** [ParticularLabs/GitVersion#168]
As discussed in #167, as tests tend to run quickly and produce more than one commit per second, it might be safer to use an explicit signature and make it shift by one second for each commit.

**Comment by JakeGinnivan** [comment]
I did this at some point.. forget when but you can see it in https://github.com/ParticularLabs/GitVersion/blob/182782e2274064049ef9c4b4632991077521f542/GitVersionCore.Tests/Helpers/Constants.cs
