### ISSUE TITLE
Build error when building from detached head should be downgraded to warning.

### ISSUE THREAD

**Issue by distantcam** [ParticularLabs/GitVersion#179]
When building from a detached head, GitVersion errors out the build and the only option is to disable GitVersion.

Instead a warning should be produced, and perhaps set the version to something like "HEAD-[SHA]" to show that this is not a normal build.

**Comment by JakeGinnivan** [comment]
Looks like #326 closes this issue.

Closing, lets create a new issue if this is still an issue.
