### ISSUE TITLE
What is the rationale behind not printing errors?

### ISSUE THREAD

**Issue by agross** [ParticularLabs/GitVersion#192]
I just started to work with gitversion (mostly from rake). I am not using a heavy workflow like gitflow, rather master + develop which I will sometimes merge.

I found the general quietness of gitversion.exe in error situations (master merged but not tagged) quite disturbing. Especially on the build server, where I cannot easily rerun the build with `/l <file>`.

Couldn't we change that and either
* print the JSON on success or
* print the log on error?

**Comment by JakeGinnivan** [comment]
Fixed by #222
