### ISSUE TITLE
use standard version for AssemblyInformationalVersion

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/GitVersion#212]
Currently the gitversiontask uses the `AssemblyInformationalVersion` attribute to stamp the assembly with some metadata

    [AssemblyInformationalVersion("5.0.0-beta.1+32.Branch.release-5.0.0.Sha.4eaaa994842b7be39ae94d4515525acfddf982f1")]

However tools actually make the incorrect assumption that AssemblyInformationalVersion will actually be a valid version number. The most current one that has bitten me is ClickOnce. Since there is not way we can correct the assumptions of other shitty tools my plan is to inject a new custom attribute and put the valid version in AssemblyInformationalVersion.

Thoughts?

**Comment by JakeGinnivan** [comment]
Maybe we could create a branch config option which is `assembly-informational-version-format` which you can go `{majorMinorPatch}.branch.{branch}` etc and we lookup variables to do the replace?

**Comment by SimonCropp** [comment]
@JakeGinnivan thinking that is the only option

**Comment by JakeGinnivan** [comment]
#368 tracks that issue
