### ISSUE TITLE
CommitsSinceTag is incorrect

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/GitVersion#213]
so CommitsSinceTag is populated by this https://github.com/Particular/GitVersion/blob/master/GitVersionCore/GitFlow/BranchFinders/OptionallyTaggedBranchVersionFinderBase.cs#L15 which is actually the "commits since branch" not "Commits Since Tag"

**Comment by JakeGinnivan** [comment]
Commit counting has completely changed.

It now counts from the source of the version. With the exception of NextVersion in the config, it falls back to the next best source for commit counting
