### ISSUE TITLE
Remove branches merge commits are not identified as valid merge commits

### ISSUE THREAD

**Issue by johnsimons** [ParticularLabs/GitVersion#217]
If we use github to merge a PR from a hotfix branch to master, GitVersion complaints that:
>The head of master should always be a merge commit if you follow gitflow. Please create one or work around this by tagging the commit with SemVer compatible Id. 

I think this should also be supported.

So the problem is that when Github does the merge, it uses the remote branch name eg `Particular/hotfix-4.6.2`, and GitVersion expects the merge to occur from a local branch.

**Comment by JakeGinnivan** [comment]
Verified this is fixed in 3.0
