### ISSUE TITLE
TagsByDate should throw if more than 1 lightweight tags are applied to the same commit

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/GitVersion#218]
so `TagsByDate` looks like this 
 
        public static IEnumerable<Tag> TagsByDate(this IRepository repository, Commit commit)
        {
            return repository.Tags
                .Where(tag => tag.PeeledTarget() == commit)
                .OrderByDescending(tag =>
                {
                    if (tag.Annotation != null)
                    {
                        return tag.Annotation.Tagger.When;
                    }
                    //lightweight tags will not have an Annotation
                    return commit.Committer.When;
                });
        }

So if more than one lightweight tag is applied to the same commit ther is no sensible order that can be applied to those tags. So it should throw an exception

**Comment by JakeGinnivan** [comment]
@SimonCropp can you check this against the 3.0 branch. Not sure it is still an issue

I just deleted `TagsByDate` as it is not used, but worth checking that the scenario has not moved elsewhere

**Comment by SimonCropp** [comment]
@GeertvanHorrik looking how all tags for a commit are now tryparsed i dont think this is an issue anymore
