### ISSUE TITLE
Support custom version tag prefix

### ISSUE THREAD

**Issue by hmemcpy** [ParticularLabs/GitVersion#228]
Currently, it seems that GitVersion will only parse the version if it has no prefixes, i.e. `1.2.3`, not `v1.2.3`.
It would be great if GitVersion supported common prefixes (mainly, v), as well as custom git-flow version prefixes (from config):
```
[gitflow "prefix"]
...
versiontag = Verz
...
```

**Comment by JakeGinnivan** [comment]
Supported via config in 3.0
