### ISSUE TITLE
Should we consider stamping AssemblyMetadataAttributes for some of our variables?

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/GitVersion#241]
http://msdn.microsoft.com/en-us/library/system.reflection.assemblymetadataattribute(v=vs.110).aspx

Or is that one step to far?

**Comment by JakeGinnivan** [comment]
Do we want this or should we close?

What would be a scenario it would be needed?

**Comment by SimonCropp** [comment]
i am calling yagni
