### ISSUE TITLE
Command line not generating proper AssemblyVersion

### ISSUE THREAD

**Issue by seankearney** [ParticularLabs/GitVersion#252]
The `AssemblyVersion` attribute appears to be generated incorrectly.

GitVersion output

	{
	  "Major":1,
	  "Minor":0,
	  "Patch":1,
	  "PreReleaseTag":"",
	  "PreReleaseTagWithDash":"",
	  "BuildMetaData":2,
	  "FullBuildMetaData":"2.Branch.master.Sha.84bbec7a3e93663b2caad2262641647e1fd27a1a",
	  "MajorMinorPatch":"1.0.1",
	  "SemVer":"1.0.1",
	  "LegacySemVer":"1.0.1",
	  "LegacySemVerPadded":"1.0.1",
	  "AssemblySemVer":"1.0.1.0",
	  "FullSemVer":"1.0.1+2",
	  "InformationalVersion":"1.0.1+2.Branch.master.Sha.84bbec7a3e93663b2caad2262641647e1fd27a1a",
	  "ClassicVersion":"1.0.1.2",
	  "ClassicVersionWithTag":"1.0.1.2",
	  "BranchName":"master",
	  "Sha":"84bbec7a3e93663b2caad2262641647e1fd27a1a",
	  "AssemblyVersion":"1.0.1.0",
	  "AssemblyFileVersion":"1.0.1.2",
	  "OriginalRelease":"84bbec7a3e93663b2caad2262641647e1fd27a1a.2014-09-10 17:22:00Z",
	  "NuGetVersionV2":"1.0.1",
	  "NuGetVersion":"1.0.1"
	}

Generated Attributes:

	[assembly: AssemblyVersion("1.0.0.0")]
	[assembly: AssemblyFileVersion("1.0.1")]
	[assembly: AssemblyInformationalVersion("1.0.1+2.Branch.master.Sha.84bbec7a3e93663b2caad2262641647e1fd27a1a")]

I would expect `[assembly: AssemblyVersion("1.0.1.0")]`

This line appears to be the issue: https://github.com/Particular/GitVersion/blob/a78ef71d41406a223a87e599e2ef9e888449b23d/GitVersionExe/AssemblyInfoFileUpdate.cs#L34

Thoughts?

**Comment by JakeGinnivan** [comment]
Pretty sure this is sorted in v2

We now default to using Major.Minor.Patch for the version (used to be Major.Minor).

You can also change this using `GitVersionConfig.yaml`.

Reopen or let us know if it is still an issue

**Comment by JakeGinnivan** [comment]
Actually, just noticed this is still not right...

 - The `AssemblyVersionFormat` argument needs to be removed
 -  `var assemblyFileVersion = variables[VariableProvider.AssemblySemVer];` -> `var assemblyFileVersion = variables[VariableProvider.AssemblyFileSemVer];`
 - assemblyVersion should be `variables[VariableProvider.AssemblySemVer];`

**Comment by JakeGinnivan** [comment]
Fixed this properly in 3.0 release branch
