### ISSUE TITLE
support for other names for tags and develop branch

### ISSUE THREAD

**Issue by PeterLehmann** [ParticularLabs/GitVersion#292]
I do like this tool, so version info is keep in git, but on this project has a other naming conv. for tags and develop branch, so we fail back to githubflow and gitflow(what are are runnign with some diff.).
so we will be lovy that you can define what prefix version tags has e.g. version-{x.y.z}
and or what the name for main develop branch is called.
i don't knwon if config or passing it into task/command is the best way.

**Comment by JakeGinnivan** [comment]
This is fully supported in 3.0.

Phew.. that was *a lot* of work...

**Comment by asbjornu** [comment]
Great work! Exactly how is this supported? Via `.yml` configuration?

**Comment by JakeGinnivan** [comment]
Yep, via the config. You can use 'GitVersion init' to generate a sample config file or 'gitversion /showConfig' to see the effective config and just override what you want to.

Sent from my Windows Phone
________________________________
