### ISSUE TITLE
GitFlow: Include commits in PreReleaseTag for release, hotfix and feature branches

### ISSUE THREAD

**Issue by yannisgu** [ParticularLabs/GitVersion#323]
For release/hotfix branches currently the PreReleaseTag  looks like this:

     -beta.1

and for feature-branches
   
      -feature-branch-name

The problem is that for every commit, the NuGet version will be the same.  My proposition is to do the same as on the develop branch: Add the number of commits (build metadata) in the pre-release tag. 

The change in the code will be trivial, but I want to hear your opinion, before I send a PR.

**Comment by JakeGinnivan** [comment]
This config approach is done. Check out the 3.0.0 branch

@remyvd I think that is a separate issue. Mind opening a new issue if it is still a problem with 3.0.0
