### ISSUE TITLE
Feature branch with GitHubFlowVersion doesn't append pre release tag

### ISSUE THREAD

**Issue by MacDennis76** [ParticularLabs/GitVersion#335]
I am testing version 2.0.0 of GitVersion, the command line version in combination with a GitHubFlow repository. This repo has a master branch and a number of feature branches.

The latest tag (on master) is equal to 1.6.0.

When working with feature branches the following is the result, in this example a feature branch called 'feature-test' is used:

{
  "Major":1,
  "Minor":6,
  "Patch":1,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "BuildMetaData":9,
  "FullBuildMetaData":"9.Branch.feature-test.Sha.747cf43601b10dd87508ba7d72a47c0e9321294b",
  "MajorMinorPatch":"1.6.1",
  "SemVer":"1.6.1",
  "LegacySemVer":"1.6.1",
  "LegacySemVerPadded":"1.6.1",
  "AssemblySemVer":"1.6.1.0",
  "AssemblyFileSemVer":"1.6.1.0",
  "FullSemVer":"1.6.1+9",
  "InformationalVersion":"1.6.1+9.Branch.feature-test.Sha.747cf43601b10dd87508ba7d72a47c0e9321294b",
  "ClassicVersion":"1.6.1.9",
  "ClassicVersionWithTag":"1.6.1.9",
  "BranchName":"feature-test",
  "Sha":"747cf43601b10dd87508ba7d72a47c0e9321294b",
  "NuGetVersionV2":"1.6.1",
  "NuGetVersion":"1.6.1"
}

Is this expected behaviour?
Because this is a pre release I would have expect a pre release tag?
This is without a NextVersion.txt file, when I add one with a version equal to '1.7.0' the following is the result:

{
  "Major":1,
  "Minor":7,
  "Patch":0,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "BuildMetaData":11,
  "FullBuildMetaData":"11.Branch.feature-test.Sha.bf90ef4e6e000dd876f47fae510052ddfae8c23d",
  "MajorMinorPatch":"1.7.0",
  "SemVer":"1.7.0",
  "LegacySemVer":"1.7.0",
  "LegacySemVerPadded":"1.7.0",
  "AssemblySemVer":"1.7.0.0",
  "AssemblyFileSemVer":"1.7.0.0",
  "FullSemVer":"1.7.0+11",
  "InformationalVersion":"1.7.0+11.Branch.feature-test.Sha.bf90ef4e6e000dd876f47fae510052ddfae8c23d",
  "ClassicVersion":"1.7.0.11",
  "ClassicVersionWithTag":"1.7.0.11",
  "BranchName":"feature-test",
  "Sha":"bf90ef4e6e000dd876f47fae510052ddfae8c23d",
  "NuGetVersionV2":"1.7.0",
  "NuGetVersion":"1.7.0"
}

My plan is to use GitVersion in combination with TeamCity and Octopus Deploy. Each feature should be deployable to a testing environment and this means that I would need to be able to also package (NuGet) and deploy pre releases (features).

So, very curious to know if this is normal behaviour.

**Comment by gep13** [comment]
@robdmoore do you think that this is related to your issue: https://github.com/ParticularLabs/GitVersion/issues/331

**Comment by robdmoore** [comment]
I think it's a duplicate, yeah.

**Comment by JakeGinnivan** [comment]
Different issue. #337 fixes it

**Comment by MacDennis76** [comment]
I tried the latest source which includes  #337. 

The result with a feature branch called feature/TOHISP-55

{
  "Major":1,
  "Minor":6,
  "Patch":1,
  "PreReleaseTag":"TOHISP-55",
  "PreReleaseTagWithDash":"-TOHISP-55",
  "BuildMetaData":2,
  "FullBuildMetaData":"2.Branch.feature/TOHISP-55.Sha.9f5ccc8addd702da2b235b202f3acf562a7b297b",
  "MajorMinorPatch":"1.6.1",
  "SemVer":"1.6.1-TOHISP-55",
  "LegacySemVer":"1.6.1-TOHISP55",
  "LegacySemVerPadded":"1.6.1-TOHISP55",
  "AssemblySemVer":"1.6.1.0",
  "AssemblyFileSemVer":"1.6.1.0",
  "FullSemVer":"1.6.1-TOHISP-55+2",
  "InformationalVersion":"1.6.1-TOHISP-55+2.Branch.feature/TOHISP-55.Sha.9f5ccc8addd702da2b235b202f3acf562a7b297b",
  "ClassicVersion":"1.6.1.2",
  "ClassicVersionWithTag":"1.6.1.2-TOHISP-55",
  "BranchName":"feature/TOHISP-55",
  "Sha":"9f5ccc8addd702da2b235b202f3acf562a7b297b",
  "NuGetVersionV2":"1.6.1-tohisp55",
  "NuGetVersion":"1.6.1-tohisp55"
}

Looks good to me.

But, this is the result when you use a hyphen in a branch called feature-TOHISP-55 which is a valid name for a branch:

{
  "Major":1,
  "Minor":7,
  "Patch":0,
  "PreReleaseTag":"",
  "PreReleaseTagWithDash":"",
  "BuildMetaData":13,
  "FullBuildMetaData":"13.Branch.feature-TOHISP-91.Sha.729e1b66f9adf293536860dc94a9272408de1004",
  "MajorMinorPatch":"1.7.0",
  "SemVer":"1.7.0",
  "LegacySemVer":"1.7.0",
  "LegacySemVerPadded":"1.7.0",
  "AssemblySemVer":"1.7.0.0",
  "AssemblyFileSemVer":"1.7.0.0",
  "FullSemVer":"1.7.0+13",
  "InformationalVersion":"1.7.0+13.Branch.feature-TOHISP-91.Sha.729e1b66f9adf293536860dc94a9272408de1004",
  "ClassicVersion":"1.7.0.13",
  "ClassicVersionWithTag":"1.7.0.13",
  "BranchName":"feature-TOHISP-91",
  "Sha":"729e1b66f9adf293536860dc94a9272408de1004",
  "NuGetVersionV2":"1.7.0",
  "NuGetVersion":"1.7.0"
}

The Stash repo has the following format:
https://stash/scm/customer/client-project.git

The following test fails:
        [Test]
        public void ShouldNotUseNumberInFeatureBranchAsPreReleaseNumberWithHyphen()
        {
            using (var fixture = new EmptyRepositoryFixture(new Config()))
            {
                fixture.Repository.MakeATaggedCommit("1.0.0");
                fixture.Repository.CreateBranch("feature-JIRA-123");
                fixture.Repository.Checkout("feature-JIRA-123");
                fixture.Repository.MakeCommits(5);

                fixture.AssertFullSemver("1.0.1-JIRA-123+5");
            }
        }

Result:

Created git repository at 'D:\web\GitVersion\GitVersionCore.Tests\bin\Release\TestRepositories\4d01858c-8426-4345-a995-9c85ca5f094e'
Running against branch: feature-JIRA-123
GitHubFlow version strategy will be used
Shouldly.ChuckedAWobbly : 
                    fixture.AssertFullSemver("1.0.1-JIRA-123+5");
        should be
    "1.0.1-JIRA-123+5"
        but was
    "1.0.1-feature-JIRA-123+5"

**Comment by JakeGinnivan** [comment]
@MacDennis76 I am working on the Config based versioning branch and hit an issue.

The above now ends up being `1.0.1-JIRA-123.1+5`. Notice the `.1`, I think that is correct.. What do you think?

**Comment by MacDennis76** [comment]
What would be the added benefit of .1 in this case? 
I understand it's usage when dealing with release branches but not directly for short lived feature branches. 

It would basically mean the first version of this feature. But how to bump it?

**Comment by JakeGinnivan** [comment]
If you release a package which is off a feature branch, it should be tagged. Once it is released the build should be producing a new version.

Without the .1 you can never release from a feature branch more than once.

**Comment by JakeGinnivan** [comment]
We would add a config property to allow skipping of the .1, but not sure that is right

**Comment by MacDennis76** [comment]
Clear, let's assume we want to release a feature branch more than once.
Then we get ..
1.0.1-JIRA-123.1+5
1.0.1-JIRA-123.2+7
1.0.1-JIRA-123.3+10
etc, right?

But we use Octopus Deploy for our deployments. Which relies on Nuget.
So, what would be the corresponding (unique) Nuget version numbers?

**Comment by JakeGinnivan** [comment]
I am working on #338 which makes this scenario a lot better.

There will be a config which switches the mode of GitVersion. There are two options, ContinuousDelivery and ContinuousDeployment. We currently are the first, where you tag each release and that causes a SemVer bump.

Continuous Deployment will bump the build metadata to be the 4th part version number. So you will get:

1.0.1.1-JIRA-123.1+1
1.0.1.2-JIRA-123.2+2
1.0.1.3-JIRA-123.3+3

Or something like that

**Comment by JakeGinnivan** [comment]
Actually. I think it is

1.0.1.1-JIRA-123+1
1.0.1.2-JIRA-123+2
1.0.1.3-JIRA-123+3

**Comment by orjan** [comment]
I think your first example is better since I don't think it's semver to add .buildnumber after the patch?

**Comment by JakeGinnivan** [comment]
Both use the 4th part.

I am not sure how else to solve the issue. The problem is this:

If we bump the patch every commit and you commit 4 times. You then get 4 packages (say 1.0.1, 1.0.2, 1.0.3, 1.0.4). Then the 4th one you use Octopus to deploy. That means that the end deployed has gone from 1.0.0 to 1.0.4 in a single release.

Our commit counting is part of the build metadata which is not part of the SemVer.

I have actually looked at the code. For pre-release we change the number on the tag. i.e

1.0.1-JIRA-123.1+1
1.0.1-JIRA-123.2+2
1.0.1-JIRA-123.3+3

But for stable packages we append a 4th part.

1.0.1.1
1.0.1.2
1.0.1.3

Thoughts on other ways to solve?

**Comment by MacDennis76** [comment]
I have a working solution for now when using TeamCity in combination with Octopus Deploy.
The main problem is that NuGet does not support Semver 2.0.0 yet. I need the NugetVersionV2 for my NuGet package but this variable does not include any build meta data.

So, I added a new variable called 'NuGetVersionV2WithCommitsSinceTag'.
This variable contains the zero padded number of commits since the last tag, only when dealing with a pre-release.

So, for a branch called JIRA-123 and 3 commits the resulting variable will be:
1.0.1-JIRA-123-0003

This is needed because Octopus Deploy and Nuget does not allow you to overwrite an existing package with the same version. Each version should be unique. In this setup I am able to utilize Continious Deployment of pre-releases.

I was inspired by this blog post:
http://www.xavierdecoster.com/semantic-versioning-auto-incremented-nuget-package-versions

**Comment by JakeGinnivan** [comment]
@MacDennis76 thanks for that link!

Very handy, especially with v3 about to drop. 

What about this (when using continuous deployment mode).
```
1.0.1-JIRA-123.1+1
1.0.1-JIRA-123.2+2
1.0.1-JIRA-123.3+3
```
The Nuget version (with current legacy semver formatting) will be
```
1.0.1-JIRA-1230001
1.0.1-JIRA-1230002
1.0.1-JIRA-1230003
```

But as you suggest rather than just pad+concat we could separate with a - making it. The rule could be if the pre-release tag ends with numbers then separate the build number by a -
```
1.0.1-JIRA-123-0001
1.0.1-JIRA-123-0002
1.0.1-JIRA-123-0003
```

Or then not padded
```
1.0.1-JIRA-123-1
1.0.1-JIRA-123-2
1.0.1-JIRA-123-3
```

Then we would have a requirement that when using the `ContinuousDeployment` option that *all* builds require pre-release tags. This means master would by default have a tag of `ci`. In fact any branch which did not have a tag configured would default to `ci`.

This means that GitVersion would always product pre-release packages except for when you tag a commit. As tagged commits always use the tag. So to release you simply tag a commit and then the tagged commit will be built by CI giving you a stable package.

That could be quite a nice solution to the problem. @xavierdecoster what are your thoughts, your blog post makes a lot of sense so I would like to put those conventions into GitVersion 3.0 to make it 'just work' for most people

**Comment by JakeGinnivan** [comment]
Ok, I have implemented this in the 3.0 release branch and documented it in the readme.

Have a read of https://github.com/ParticularLabs/GitVersion/tree/release/3.0.0#continuousdeployment and give me your thoughts. I am also going to push the button on 3.0.0-rc.1 shortly so you can give that a spin and see if it allows you to remove your workarounds :)

Appreciate everyones help and anymore feedback on the subject (especially how 3.0 works for you) is more than welcome

**Comment by robdmoore** [comment]
Really interesting that you can roll your own config. Probably a good thing. I wonder if you are using the two common strategies (gitflow and githubflow) if there can be a shorthand for that so you don't have to study the config file to try and figure out what you are using?

--
Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net

**Comment by JakeGinnivan** [comment]
It has default config included which will make it work the same as now. But if someone has different requirements then they can change it.

The main reason for this change is predictability, all branches have the same code and just different config.

Have a read through the readme on the 3.0.0 branch and are if it makes sense.

Sent from my Windows Phone
________________________________

**Comment by robdmoore** [comment]
It does make sense, but I'm not sure if it does what I mean.

I want it to either take a switch in the config (mode?) that sets up default rules without having to specify them or (even better) of rules aren't specified then use the current logic of detecting a develop branch to automatically apply the relevant rules.

Having to call init to get the file is fine if you have one or two repos, but if you have 20 then it's a pain. Similarly if there is an error in the current defaults that get output that later needs to be corrected. I'm using Git hub flow - it's a well known and understood thing - I don't think I need to have or see the specific branch configs for it in the yaml file.

Thoughts?

**Comment by JakeGinnivan** [comment]
Default rules are in the code, not in your GitVersion.yaml.

GitVersion unit creates an sample file which is commented out.

The config file is only for overriding which most people shouldn't do

Sent from my Windows Phone
________________________________

**Comment by robdmoore** [comment]
Oh sweet! So exactly what I wanted then!

Carry on ;)

**Comment by MacDennis76** [comment]
Great work so far on 3.0.0! I very much like the direction this tool is heading.
Anyway, testing out the latest 3.0 release branch ..

For a branch called TOHISP-35 (a JIRA key) and 27 commits ahead, this results in the following NuGetVersion in Continuous Deployment mode:
1.6.1-TOHISP-350027

But how do I add a hyphen after '35'? The version now doesn't make much sense.
Shouldn't this be by default? If a branch ends with a number then add a hyphen?

**Comment by JakeGinnivan** [comment]
What variable are you using?

I can't replicate that.. This is what I get when I checkout `feature/JIRA-1234` and run it

```
{
  "Major":3,
  "Minor":0,
  "Patch":0,
  "PreReleaseTag":"JIRA-1234.1",
  "PreReleaseTagWithDash":"-JIRA-1234.1",
  "BuildMetaData":867,
  "FullBuildMetaData":"867.Branch.feature/JIRA-1234.Sha.73ce17303ad7d775a9dd963000baf88e8b83d634",
  "MajorMinorPatch":"3.0.0",
  "SemVer":"3.0.0-JIRA-1234.1",
  "LegacySemVer":"3.0.0-JIRA-1234-1",
  "LegacySemVerPadded":"3.0.0-JIRA-1234-0001",
  "AssemblySemVer":"3.0.0.0",
  "FullSemVer":"3.0.0-JIRA-1234.1+867",
  "InformationalVersion":"3.0.0-JIRA-1234.1+867.Branch.feature/JIRA-1234.Sha.73ce17303ad7d775a9dd963000baf88e8b83d634",
  "BranchName":"feature/JIRA-1234",
  "Sha":"73ce17303ad7d775a9dd963000baf88e8b83d634",
  "NuGetVersionV2":"3.0.0-jira-1234-0001",
  "NuGetVersion":"3.0.0-jira-1234-0001"
}
```

**Comment by MacDennis76** [comment]
Seems I didn't pull the latest changes, sorry for that. After a pull and rebuild it is now working as expected! :)

Will continue my testing the coming days.

**Comment by JakeGinnivan** [comment]
Awesome!

**Comment by MacDennis76** [comment]
Has 3.0.0 yet been tested with the dynamic repository feature? Seems to be broken to me.
I need this feature because of TeamCity and agent-side checkouts.
It worked fine in 2.0.0, need to do more testing though.

**Comment by MacDennis76** [comment]
Looking at the TOSHIP-35 GIT history it becomes clear that the branching from master was not recorded. This repo has been converted from a SVN repository some months ago.

In such case the logic which tries to find the parent branches (InheritBranchConfiguration) also included the current branch.

With that in mind, the following piece of code right after the codes which finds the parent branches, seems to do the trick:

```
            // In some cases a found parent can include the current branch
            if (possibleParents.Count > 0 && possibleParents.Any(p => p.Name == currentBranch.Name))
            {
                possibleParents.Remove(possibleParents.Single(p => p.Name == currentBranch.Name));
            }
```

With this code the master configuration is inherited

**Comment by MacDennis76** [comment]
Has 3.0.0 yet been tested with the dynamic repository feature? Seems to be broken to me.
I need this feature because of TeamCity and agent-side checkouts.
It worked fine in 2.0.0, need to do more testing though.

It seems to end up in a loop when checking out a feature branch with the following GitVersionConfig.yaml file:

```
assembly-versioning-scheme: MajorMinorPatchMetadata
# tag-prefix: '[vV|version-] # regex to match git tag prefix
# next-version: 1.0.0
mode: ContinuousDeployment
# continuous-delivery-fallback-tag: ci
#branches:
#   release[/-]*:
#   mode: ContinuousDelivery | ContinuousDeployment
#    tag: rc
#   develop:
#    mode: ContinuousDelivery | ContinuousDeployment
#    tag: alpha
```

Ouput which repeats ..

```
Fetching from remote 'origin' using the following refspecs: +refs/heads/*:refs/remotes/origin/*.
Creating local branch from remote tracking 'refs/remotes/origin/feature/TOHISP-35'.
Creating local branch from remote tracking 'refs/remotes/origin/feature/TOHISP-91'.
Creating local branch from remote tracking 'refs/remotes/origin/Localizing'.
Skipping local branch creation since it already exists 'refs/remotes/origin/master'.
HEAD points at branch 'refs/heads/master'.
Switching to branch 'feature/TOHISP-91'
Checking out files that might be needed later in dynamic repository
  Trying to check out 'NextVersion.txt'
Checking out files that might be needed later in dynamic repository
  Trying to check out 'GitVersionConfig.yaml'
Working directory: D:\web\Tommy\Sitecore\Source\_dynamicrepository
Attempting to inherit branch configuration from parent branch
Found possible parent branches: feature/TOHISP-35, master
Attempting to inherit branch configuration from parent branch
Found possible parent branches: feature/TOHISP-35, master
Attempting to inherit branch configuration from parent branch
Found possible parent branches: feature/TOHISP-35, master
Attempting to inherit branch configuration from parent branch
Found possible parent branches: feature/TOHISP-35, master
```

Trying the master branch does work though.

**Comment by MacDennis76** [comment]
Looking back at the TOSHIP-35 GIT history it becomes clear that the branching from master was not properly recorded in this repo.

In such case the logic which tries to find the parent branches (InheritBranchConfiguration) also included the current branch.

With that in mind, the following piece of code right after the codes which finds the parent branches, seems to do the trick:

```
            // In some cases a found parent can include the current branch
            if (possibleParents.Count > 0 && possibleParents.Any(p => p.Name == currentBranch.Name))
            {
                possibleParents.Remove(possibleParents.Single(p => p.Name == currentBranch.Name));
            }
```

With this code the master configuration is inherited

**Comment by JakeGinnivan** [comment]
The 3.0 stuff has @GeertvanHorrik's dynamic repo pull request merged. @GeertvanHorrik any ideas?

**Comment by JakeGinnivan** [comment]
@MacDennis76 can you post the log. or create a simple test which shows the issue?

**Comment by MacDennis76** [comment]
Unfortunately not possible to share logs because this is a customer repo.

**Comment by JakeGinnivan** [comment]
Check out contributing.md, it explains the tests. You might be able to reproduce issue in a test?

It would be good to get a test to prevent regression again

Sent from my Windows Phone
________________________________

**Comment by GeertvanHorrik** [comment]
We need a test in order to reproduce. I am using it all over the place (but must admit that I am using a custom build). Will try the latest now.

**Comment by JakeGinnivan** [comment]
The tests that were written in the PR are passing. Make sure you check the release/3.0.0 branch

**Comment by GeertvanHorrik** [comment]
It seems to work right here.

**Comment by JakeGinnivan** [comment]
Sweet, thanks for testing. More people that test this release the better. Lots of changes :P

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik sorry for pulling you in, definitely looks like an issue with the branch config inheritance not remote repo stuff..

**Comment by GeertvanHorrik** [comment]
np, always happy to help on such a nice project ;-)

**Comment by MacDennis76** [comment]
Problem keeps getting back, also with other branches.
Only seems to be occuring with a dynamic repository, I can't reproduce it with a local checkout.
Also, seems to occur when you merge master in your feature branch.
Master is my main branch, I am using GitHub flow.

**Comment by JakeGinnivan** [comment]
@MacDennis76 I have made some changes to that branch inheritance code in `release/3.0.0`. Could you retest it?

**Comment by MacDennis76** [comment]
Tested, now correctly falls back to the master branch.

**Comment by JakeGinnivan** [comment]
![Yes...](http://media.giphy.com/media/TsD8LGhM5jgs0/giphy.gif)
