### ISSUE TITLE
Eat your own dog food for GitVersion

### ISSUE THREAD

**Issue by GeertvanHorrik** [ParticularLabs/GitVersion#370]
Why isn't there a develop branch on GitVersion? Isn't it a good idea to EYODF?

**Comment by JakeGinnivan** [comment]
GitVersion uses GitHubFlow which is also supported. We can't support multiple branching strategies. The GitVersion build does indeed dogfood itself, it builds itself, runs the build output to version itself then builds again. 

That said Particular use GitFlow extensively and do test it in a GitFlow environment before release.

**Comment by GeertvanHorrik** [comment]
Excellent, we do the same, then it's covered for sure. Thanks for the info!

**Comment by JakeGinnivan** [comment]
When I say can't support multiple branching strategies, I mean that we can't have multiple strategies in a single repo
