### ISSUE TITLE
Branches with uppercase confuse the version extraction from merge commit

### ISSUE THREAD

**Issue by anobleperson** [ParticularLabs/GitVersion#375]
Branches with uppercase confuse the version extraction from merge commit. If the release branch has upper case prefix, the version number cannot be extracted.

This test passes:
    [Test]
    public void CanHandleReleaseBranchWithStability()
    {
        using (var fixture = new EmptyRepositoryFixture(new Config()))
        {
            fixture.Repository.MakeATaggedCommit("1.0.3");
            fixture.Repository.CreateBranch("develop");
            fixture.Repository.MakeCommits(5);
            fixture.Repository.CreateBranch("release-2.0.0-Final");
            fixture.Repository.Checkout("release-2.0.0-Final");

            fixture.AssertFullSemver("2.0.0-beta.1+5");
        }
    }

This test fails:
    [Test]
    public void CanHandleReleaseBranchWithStability()
    {
        using (var fixture = new EmptyRepositoryFixture(new Config()))
        {
            fixture.Repository.MakeATaggedCommit("1.0.3");
            fixture.Repository.CreateBranch("develop");
            fixture.Repository.MakeCommits(5);
            fixture.Repository.CreateBranch("Release-2.0.0-Final");
            fixture.Repository.Checkout("Release-2.0.0-Final");

            fixture.AssertFullSemver("2.0.0-beta.1+5");
        }
    }

**Comment by JakeGinnivan** [comment]
Fixed in >3.0.0-beta.1 (unreleased)
