### ISSUE TITLE
Commits since tag should not be in the build meta data but in the pre-release tag

### ISSUE THREAD

**Issue by eggapauli** [ParticularLabs/GitVersion#384]
According to the semver 2.0 spec

> Precedence refers to how versions are compared to each other when ordered. Precedence MUST be calculated by separating the version into major, minor, patch and pre-release identifiers in that order __(Build metadata does not figure into precedence).__ Precedence is determined by the first difference when comparing each of these identifiers from left to right as follows: Major, minor, and patch versions are always compared numerically. Example: 1.0.0 < 2.0.0 < 2.1.0 < 2.1.1. When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0. Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

This means that

"1.3.0-beta.1+39" is at the same precedence as  "1.3.0-beta.1+4"

As GitVersion places the __commits since tag__ into the build meta data there is no __to spec__ way of ordering versions created with GitVersion on a single branch. This causes us problems because we build an installer in our CI system and distribute it internally for testing. The installer must grab the use the semver to detect if it needs to upgrade or not.

If the __commit since tag__ is placed into the pre release then it becomes part of the ordering.

"1.3.0-beta.1.39" is of higher precedence than  "1.3.0-beta.1.4"

We could fix this in the source and send a pull request but thought we should check with you first. Perhapps you have some good reason for putting the __commits since tag__ in the build meta data that we are unaware of.

**Comment by JakeGinnivan** [comment]
Yep, so this issue is the main motivation for v3.0

https://github.com/ParticularLabs/GitVersion/tree/release/3.0.0#octopus-deployci-build-nuget-packages

Just upgrade to GitVersion 3.0.0-beta.1 - feedback is welcome as it would be good to release the stable once we get more feedback

**Comment by eggapauli** [comment]
I see it now. Nice!

**Comment by JakeGinnivan** [comment]
Let me know how it works out for you!

**Comment by JakeGinnivan** [comment]
Also, feedback on new readme and how discoverable the info is would also be appreciated
.

**Comment by eggapauli** [comment]
The docs seem to be a bit different from the actual config file generated by `GitVersion init`, but I assume you will synchronize them when you release v3.
More examples for the config file would be helpful. A wizard to generate the config file would have helped us.
Also a comparison of the two modes `ContinuousDelivery` and `ContinuousDeployment` in a table would be helpful.
But we're impressed how fast you respond and how customizable v3 is. Thanks a lot!

**Comment by JakeGinnivan** [comment]
The init is just a simple sample. if you use `/showConfig` that will show the current actual config. You can copy then modify that if you want.

PR's on the docs/readme are useful too :) I like the idea of the comparison table I will do that
