### ISSUE TITLE
IP nummer in merge messages is treated as versions

### ISSUE THREAD

**Issue by orjan** [ParticularLabs/GitVersion#395]
Running some regression tests against master version 3.beta-1 and found that GitVersion will use IP-numbers in our merge commits as versions. MergeMessageBaseVersionStrategy is really powerful but also a little bit dangerous.

```csharp
        [Test]
        public void AMergeCommitIncludingAnIpNumberShouldNotBeParsedAsAVersion()
        {
            var mergeCommitWithIpNumber = @"Merge pull request #45 in BRIKKS/brikks from feature/NOX-68 to develop

* commit '38560a7eed06e8d3f3f1aaf091befcdf8bf50fea':
  Another commit message
  Commit message including a IP-number https://10.50.1.1
  A commit message";

            var parents = GetParents(true);

            AssertMergeMessage(mergeCommitWithIpNumber, null, parents);
        }
```

**Comment by orjan** [comment]
I'm pretty sure this issue was introduced in https://github.com/ParticularLabs/GitVersion/commit/c96b55bebca7f311f70bf9a841bb6a2e595b7246

**Comment by JakeGinnivan** [comment]
Related to #385 - this is something we need to address before pushing v3.0
