### ISSUE TITLE
With large repositories it is slow to delete and reclone the dynamic directory every time

### ISSUE THREAD

**Issue by eggapauli** [ParticularLabs/GitVersion#398]
We have a repo with about 200MB in it. 

When running on our build server ( teamcity ) GitVersion tries to create a dynamic repository by freshly cloning the whole repo on every build. This is very inefficient as it tries to pull the whole repo from github every time. GitVersion should have an option to specify a directory where a local clone can be maintained and then if the directory exists only a fetch will be needed to freshen the contents.

**Comment by eggapauli** [comment]
Our current work-around is the following:

Before running GitVersion as part of our build, we update a local mirror repository with the latest changes (so we either clone or fetch from the remote repository). Then we run GitVersion on this repository (just with the /b switch) so it can't complain about missing master branches or anything else and tells TeamCity the correct version.  
But GitVersion is smart and detects that we run under TeamCity (because TEAMCITY_VERSION is set), so before running GitVersion we remove this variable and reset it after GitVersion finished running.
Obviously that's a dirty, dirty hack we are not really happy with.

We really would be glad if GitVersion allowed the _dynamicrepository to be
  * at a specified location
  * not deleted, but just updated

**Comment by JakeGinnivan** [comment]
Maybe by default we should just use %tmp% which is per user?

I think it makes sense to move it out of the teamcity work directory. And also allow it to be overriden

**Comment by eggapauli** [comment]
Yeah, that makes perfect sense to put it in the tmp directory.
For us, it is most important that it doesn't get deleted on every build.

**Comment by robdmoore** [comment]
How would GitVersion determine what folder in tmp to put it in?

**Comment by eggapauli** [comment]
Use the same rule that git clone uses I guess. Takes the last part of the remote origin URL minus the .git

**Comment by JakeGinnivan** [comment]
@eggapauli @GeertvanHorrik can you guys review https://github.com/ParticularLabs/GitVersion/pull/399

**Comment by GeertvanHorrik** [comment]
It doesn't solve the issue I think:

1) You delete the directory if it exists in the GitPreparer
2) You delete the directory once the version is calculated

I think the idea is to clone (bare) if required. If there already is a git directory, pull the latest changes and search for the required commit.

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik yeah, have not really finished. But the logic of where to put the dynamic repo and such?

**Comment by GeertvanHorrik** [comment]
```
      var repositoryName = targetUrl.EndsWith(".git") ?
+                targetUrl.Split('/', '\\').Last().Replace(".git", string.Empty) :
+                targetUrl.Split('/', '\\').Last();
```

I think this can be a bit improved. Why don't you do something like this:

```
var repositoryName = targetUrl.Split('/', '\\').Last().Replace(".git", string.Empty);
```

The rest looks good so far.

**Comment by eggapauli** [comment]
Didn't try it, but looks good so far. Also made one comment on the PR.
