### ISSUE TITLE
StackOverflowException when two feature branches are pointing to the same commit

### ISSUE THREAD

**Issue by eggapauli** [ParticularLabs/GitVersion#411]
I made a mistake and set two feature branches to point to the same commit. When running `gitversion` on one of the branches it crashes with a `StackOverflowException`. Of course this is my mistake because two feature branches shouldn't point to the same commit, but maybe you can detect and break the recursion (or whatever the exception triggers).

Run the following commands to reproduce the issue:

    mkdir stackoverflowtest
    cd .\stackoverflowtest
    git init
    git commit --allow-empty -m "Commit 1"
    git checkout -b develop
    git checkout -b feature/feature1
    git commit --allow-empty -m "Commit 2"
    git commit --allow-empty -m "Commit 3"
    git checkout -b feature/feature2
    gitversion # This will take some time and then crash with a StackOverflowException
    cd ..
    rm -Force -Recurse .\stackoverflowtest

The version of GitVersion is used was 3.0.0-Beta1.

**Comment by nulltoken** [comment]
Can you please share the complete stack trace?

**Comment by JakeGinnivan** [comment]
@nulltoken this will likely be my branch inheriting code as it is recursive. I will create a repro test and fix

**Comment by eggapauli** [comment]
I don't get a complete stack trace when I run this from the command line, but I could probably checkout the branch and run it with an attached debugger if you want me to?
