### ISSUE TITLE
Dynamic repository checkout doesn't work with /updateassemblyinfo

### ISSUE THREAD

**Issue by MattDavies** [ParticularLabs/GitVersion#412]
When using dynamic repository checkouts with the executable, /updateassemblyinfo doesn't update AssemblyInfo files.

From what I can see, it appears as though GitVersion searches the git checkout directory for the AssemblyInfo files (which in this case, is the subfolder containing the dynamic repository) rather than the current or provided working directory.

Happy to do a PR - just wanted to confirm I'm not going crazy first.

cc @JakeGinnivan

**Comment by JakeGinnivan** [comment]
This is merged to master. If you can try building from master. I don't think I will be able to get a release out tonight, but I will try
