### ISSUE TITLE
Question: Does GitVersionTask output to Build server?

### ISSUE THREAD

**Issue by crakinshot** [ParticularLabs/GitVersion#413]
Does the nuget GitVersionTask do the same as GitVersion.exe /output buildserver, in so far as allowing me to then use the parameters in TeamCity?

**Comment by JakeGinnivan** [comment]
It should detect it is running in TeamCity automatically and write the variables out. The reason for the switch on the exe is that we can return a JSON object which holds all the variables. Reopen this issue if this is not the case

**Comment by crakinshot** [comment]
Cheers. I had it working for one project, but not another. Fixed my issue, anyhow. All working.
