### ISSUE TITLE
GitHubFlow and GitFlow links around wrong way on site

### ISSUE THREAD

**Issue by bzbetty** [ParticularLabs/GitVersion#414]
http://particularlabs.github.io/GitVersion/
In the menu the gitflow items like to githubflow and vice versa

**Comment by gep13** [comment]
Good catch!

@JakeGinnivan where is the code for that site hosted?

**Comment by JakeGinnivan** [comment]
Should be the gh-pages branch

Sent from my Windows Phone
________________________________

**Comment by gep13** [comment]
Doh! Never thought to look there, I was looking for a separate repo.

Fixed the links.

**Comment by gep13** [comment]
Thanks for reporting this @bzbetty
