### ISSUE TITLE
Incorrect PR version in 3.0

### ISSUE THREAD

**Issue by JakeGinnivan** [ParticularLabs/GitVersion#415]
We have released `3.0.0-beta.1` but not `3.0.0`. So pull requests should be versioned `3.0.0-pullrequest.000` rather than `3.0.1-pullrequest.000`

**Comment by JakeGinnivan** [comment]
https://github.com/ParticularLabs/GitVersion/pull/394 should have fixed.

**Comment by GeertvanHorrik** [comment]
Not sure if I agree. Will the PR be included in 3.0.0 or 3.0.1? That depends. The question is what should be done with the default (I think next, as soon as you release a beta (release branch), you only want fixes, right)?

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik if the PR is merged before 3.0.0 is released then yes. If 3.0 is released then if the PR gets rebuilt it will be rebuilt as 3.0.1
