### ISSUE TITLE
Question: How to use Continous Deployment with GitVersionTask?

### ISSUE THREAD

**Issue by MeirionHughes** [ParticularLabs/GitVersion#417]
My workflow is to automatically deploy anything from the master or release-* (as pre-release) to nuget (teamcity). I noticed as I commit changes to a release branch that the -beta1 isn't incrementing. 

I think I've read that I need to switch to Continuous Deployment mode, but I couldn't see how to do this if I'm just using GitVersionTask off nuget.

**Comment by JakeGinnivan** [comment]
The GitVersionTask will still respect the GitVersionConfig.yaml file if your project root. Just create the config file using the information at https://github.com/ParticularLabs/GitVersion#branch-configuration

Feel free to submit a pull request or update our docs to help others find this info :)

**Comment by crakinshot** [comment]
hmm can't seem to bring up the default config. *GitVersion showConfig* and *GitVersion /showConfig* both result in *Failed to prepare or find the .git directory in path '/showConfig'*

**Comment by gep13** [comment]
Can you grab a screenshot of the command window where you are running the command?  Also, what is the complete command that you are running?  Are you using the targetPath parameter?

The error that you are getting suggests that GitVersion has been unable to locate the .git folder which git manages behind the scenes for you.  This can happen when you have specified the wrong targetPath parameter, or you are running GitVersion on the command line in the incorrect directory.

**Comment by crakinshot** [comment]
Nothing special, installed via Chocolaty - although I had to skip some step because its not working properly. Ran this is admin cmd... 

D:\Code\RobGeoLtd\Data.Components>GitVersion
{
  "Major":0,
  "Minor":4,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "BuildMetaData":2,
  "FullBuildMetaData":"2.Branch.release/release-0.4.Sha.ec8690f9dc6b5ac715d0f40669cd5ef33febfc54",
  "MajorMinorPatch":"0.4.0",
  "SemVer":"0.4.0-beta.1",
  "LegacySemVer":"0.4.0-beta1",
  "LegacySemVerPadded":"0.4.0-beta0001",
  "AssemblySemVer":"0.4.0.0",
  "AssemblyFileSemVer":"0.4.0.0",
  "FullSemVer":"0.4.0-beta.1+2",
  "InformationalVersion":"0.4.0-beta.1+2.Branch.release/release-0.4.Sha.ec8690f9dc6b5ac715d0f40669cd5ef33febfc54",
  "ClassicVersion":"0.4.0.2",
  "ClassicVersionWithTag":"0.4.0.2-beta.1",
  "BranchName":"release/release-0.4",
  "Sha":"ec8690f9dc6b5ac715d0f40669cd5ef33febfc54",
  "NuGetVersionV2":"0.4.0-beta0001",
  "NuGetVersion":"0.4.0-beta0001"
}

D:\Code\RobGeoLtd\Data.Components>GitVersion showConfig
Failed to prepare or find the .git directory in path 'showConfig'

**Comment by gep13** [comment]
ah, hold on....

What version of GitVersion have you got installed?  Are you using the latest pre-release version, i.e. 3.0.0-beta2?

To install this from chocolatey, you will need to do:

```choco install gitversion.portable -pre -y```

I suspect you might have an earlier version, that isn't recognising the ```/showconfig``` command.  But that is just a guess at this point.

**Comment by crakinshot** [comment]
with -y it fails, so with -n to stop the script it runs... but its still installing 2.0.1

>
choco install gitversion.portable -pre -n --force
Chocolatey v0.9.9.4
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.

GitVersion.Portable v2.0.1 (forced)
 ShimGen has successfully created a shim for GitVersion.exe
 gitversion.portable has been installed successfully.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details.

D:\Code\RobGeoLtd\Data.Components>

**Comment by gep13** [comment]
Hmm, that is very strange, hold on... let me try something...

**Comment by gep13** [comment]
Hmm, I have just tried this:

```
C:\github\Organisations\chocolatey> choco install gitversion.portable -pre -y -n
Chocolatey v0.9.9.4
Installing the following packages:
gitversion.portable
By installing you accept licenses for the packages.

GitVersion.Portable v3.0.0-beta0002
 ShimGen has successfully created a shim for GitVersion.exe
 gitversion.portable has been installed successfully.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details.
```

And it works as expected.  Can you try without the ```--force```.  You shouldn't need that.  The need for ```-n``` is a known issue which I raised an issue about this morning:

https://github.com/chocolatey/choco/issues/230

The problem being that GitVersion is/was actually using an undocumented method that was never part of the Public API of Chocolatey.  We have taken the decision to add this method into the public API, but the current implementation doesn't work correctly yet, we are working on it though.

**Comment by crakinshot** [comment]
Without --force its the same. (just doesn't install - already installed). I'm on windows 7 btw. Are versions limited to OS at all? 

Admittedly, I'm new to this. I installed Chocolaty in an admin cmd prompt. It seemed to install happily.

**Comment by gep13** [comment]
No, the OS shouldn't make any difference.  I am running on Windows 7 as well.

Ok, do this for me...

* Go to C:\ProgramData\chocolatey\lib
* Find any folders with GitVersion.Portable, and delete them
* Go to C:\ProgramData\chocolatey\lib-bad
* Find any folders with GitVersion.Portable, and delete them
* Go to C:\ProgramData\chocolatey\lib-bkp
* Find any folders with GitVersion.Portable, and delete them
* Go to C:\Users\All Users\chocolatey\bin
* If there are any files starting with Gitversion, delete them
* If there are any files starting with gfv, delete them

After all that, close you console/powershell window and run the following command:

```choco install gitversion.portable -pre -y -n```

And hopefully that will get you back to a known state.

**Comment by crakinshot** [comment]
Phew... finally, choco install gitversion.portable -version 3.0.0-beta0002 -pre with skip did the trick. Got the config. :)

**Comment by gep13** [comment]
Woot! :+1:

**Comment by crakinshot** [comment]
Okay cool this all seems to be working now. Commits to an active release-branch is upping the beta version number. I think I may have had some issues by messing with tags manually. After closing and opening a new release via SourceTree, it all seems to be working well. Thank you. :)

**Comment by crakinshot** [comment]
Sorry, spoke too soon. I have some odd behavior with the BuildMetaData number. If I've just been working locally the beta number moves up with each commit as I'm expecting: 

![Tree] (http://i.imgur.com/G3ZpeuG.png)
>
  "Major":0,
  "Minor":6,
  "Patch":0,
  "PreReleaseTag":"beta.4",
  "PreReleaseTagWithDash":"-beta.4",
  "BuildMetaData":4,
  "FullBuildMetaData":"4.Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "MajorMinorPatch":"0.6.0",
  "SemVer":"0.6.0-beta.4",
  "LegacySemVer":"0.6.0-beta4",
  "LegacySemVerPadded":"0.6.0-beta0004",
  "AssemblySemVer":"0.6.0.0",
  "FullSemVer":"0.6.0-beta.4",
  "InformationalVersion":"0.6.0-beta.4+Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "BranchName":"release/release-0.6",
  "Sha":"061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "NuGetVersionV2":"0.6.0-beta0004",
  "NuGetVersion":"0.6.0-beta0004"

However, if I now push the release branch onto the remote server and run GitVersion I get this: 

>
  "Major":0,
  "Minor":6,
  "Patch":0,
  "PreReleaseTag":"beta.1",
  "PreReleaseTagWithDash":"-beta.1",
  "BuildMetaData":1,
  "FullBuildMetaData":"1.Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "MajorMinorPatch":"0.6.0",
  "SemVer":"0.6.0-beta.1",
  "LegacySemVer":"0.6.0-beta1",
  "LegacySemVerPadded":"0.6.0-beta0001",
  "AssemblySemVer":"0.6.0.0",
  "FullSemVer":"0.6.0-beta.1",
  "InformationalVersion":"0.6.0-beta.1+Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "BranchName":"release/release-0.6",
  "Sha":"061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "NuGetVersionV2":"0.6.0-beta0001",
  "NuGetVersion":"0.6.0-beta0001"

**Comment by gep13** [comment]
Can you confirm that the same version of GitVersion is being used both locally, and on the server?

Sent from my Windows Phone
________________________________

**Comment by crakinshot** [comment]
I was running GitVersion locally (same cmd prompt) both times. All I did was to have git push the branch onto the remote origin. I then ran GitVersion again locally and the beta number changed down from 4 to 1.

**Comment by JakeGinnivan** [comment]
Can you run `gitversion /l console`

It will log out some information which might help diagnose

**Comment by crakinshot** [comment]
Before Pushing to Origin: 
>
061020d (release/release-0.6)
bc7924f
57e8ffc
e87307f
7d66f6c (origin/develop)(develop)

Output:
> 
  "FullBuildMetaData":"4.Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",
  "MajorMinorPatch":"0.6.0",

Log: 
>
Working directory: D:\Code\RobGeoLtd\Data
No specific commit specified or found, falling back to latest commit on specified branch
Running against branch: release/release-0.6
Base Versions:
Fallback base version: 0.1.0 from commit 8854f36d33709570d2b4c665655b9db77c4dc885
Git tag 'release-0.4': 0.4.0 from commit 254f4b8d38e894553bd1d07d53d2327eed608b4c
Git tag 'release-0.4': 0.4.0 from commit 254f4b8d38e894553bd1d07d53d2327eed608b4c
Version in branch name: 0.6.0 from commit 7d66f6c129405aa142bbe04c7bc414ca5fdc98c3
Base version used: Version in branch name: 0.6.0 from commit 7d66f6c129405aa142bbe04c7bc414ca5fdc98c3
Skipping version increment

After push to Origin
>
061020d (origin/release/release-0.6)(release/release-0.6)
bc7924f
57e8ffc
e87307f
7d66f6c (origin/develop)(develop)

Output:
>
  "BuildMetaData":1,
  "FullBuildMetaData":"1.Branch.release/release-0.6.Sha.061020d8e0a36ccc5bed1885a4bddbcc6cd15319",

Log
>Working directory: D:\Code\RobGeoLtd\Data
No specific commit specified or found, falling back to latest commit on specified branch
Running against branch: release/release-0.6
Base Versions:
Fallback base version: 0.1.0 from commit 8854f36d33709570d2b4c665655b9db77c4dc885
Git tag 'release-0.4': 0.4.0 from commit 254f4b8d38e894553bd1d07d53d2327eed608b4c
Git tag 'release-0.4': 0.4.0 from commit 254f4b8d38e894553bd1d07d53d2327eed608b4c
Version in branch name: 0.6.0 from commit bc7924f517fe7fc41d4371b9f000963adb54a6c4
Base version used: Version in branch name: 0.6.0 from commit bc7924f517fe7fc41d4371b9f000963adb54a6c4
Skipping version increment

**Comment by MeirionHughes** [comment]
So is this a bug or working as intended? If its a bug I'll have a go fixing it. But its not clear.

**Comment by JakeGinnivan** [comment]
I think it's a bug... It doesn't look right

**Comment by MeirionHughes** [comment]
I've tried to test for it, but I can't seem to get pushing to a remote right :(

LibGit2Sharp complains you cant push to "Local push doesn't (yet) support pushing to non-bare repos."

https://github.com/MeirionHughes/GitVersion/commit/d69c1e8562e78f849877567f1c2b0cfe3062c535

**Comment by MeirionHughes** [comment]
I think I've found the problem. In Extensions-> FindCommitBranchWasBranchedFrom

```C#
c.GetBranchesContainingCommit(repository, onlyTrackedBranches).ToList()
```

...includes the remote branch as well as the local. So the count is higher than if the remote branch was behind or not on remote.

**Comment by MeirionHughes** [comment]
Test and Fix: https://github.com/ParticularLabs/GitVersion/pull/442
