### ISSUE TITLE
Stale dynamic repo cache

### ISSUE THREAD

**Issue by MattDavies** [ParticularLabs/GitVersion#418]
In 3.0.0-beta0002 it looks like caching for the dynamic repository was added, but that cache is never updated over time and becomes stale. As an example when new tags are added in the remote, GitVersion doesn't seem to see them in it's cached copy of the repository and we needed to manually delete the dynamic repo cache first to get a correct version number result.

I'm guessing it's related to this: https://github.com/ParticularLabs/GitVersion/pull/399#discussion-diff-26903087 but I haven't had a chance to investigate further yet.

**Comment by JakeGinnivan** [comment]
Hrrm, maybe normalise doesn't fetch.. damn
