### ISSUE TITLE
[Question] - how does GitVersion update TeamCity build variables when the exe is called?

### ISSUE THREAD

**Issue by dazinator** [ParticularLabs/GitVersion#419]
I am just wondering if you can point me to the code or give a quick explaination for how GitVersion manages to modify the Team City version variables when the exe is invoked during a team city build step!?

**Comment by JakeGinnivan** [comment]
TeamCity (and other build servers) monitor the standard out for specially formatted messages which get interpreted as commands.

https://github.com/ParticularLabs/GitVersion/blob/master/GitVersionCore/BuildServers/TeamCity.cs#L33 is where it happens. And it's documented at https://confluence.jetbrains.com/display/TCD8/Build+Script+Interaction+with+TeamCity

**Comment by gep13** [comment]
NOTE:  This will only happen if you specify the output buildserver parameter as per this example:

https://github.com/ParticularLabs/GitVersion/wiki/Command-Line-Tool#directly-on-build-server

**Comment by dazinator** [comment]
Ahhh oooook - cheers guys

**Comment by MeirionHughes** [comment]
If it helps, I used this originally https://github.com/JetBrains/meta-runner-power-pack/tree/master/gitversion
but now I just use the GitVersionTask off nuget.

**Comment by gep13** [comment]
That's a good shout @MeirionHughes, I should have mentioned the meta runner :+1: 

@dazinator we ok to close this?

**Comment by dazinator** [comment]
Yep - all good now - closing ;)
