### ISSUE TITLE
GitVersionTask targets file doesn't have way to override with NoFetch option

### ISSUE THREAD

**Issue by MarkZuber** [ParticularLabs/GitVersion#431]
The GitVersionTask.targets file doesn't have a way to set a variable such that we can override and send in the NoFetch parameter which goes to the task.  And since referencing the nuget package automatically runs GitVersion (which is awesome), I can't setup the task to behave the way I need it to (not awesome).

Expected that there would be a 
<Input TaskParameter="NoFetch" PropertyName="$(GitVersionNoFetchValue)"/>

and your targets default GitVersionToFetchValue to false if it's not already set somewhere else.

**Comment by JakeGinnivan** [comment]
#440 fixed this. Thanks @asbjornu 

You can build from master, otherwise I hope to get a release out tonight
