### ISSUE TITLE
Inclusion of Build Server metadata

### ISSUE THREAD

**Issue by deyvsh** [ParticularLabs/GitVersion#433]
Historically I've used a build-server-generated index ("build counter") as part of the build metadata, for a few reasons:

 - In .NET world it's possible for the state of the build server (agent) to affect the output binaries (e.g. if referenced assemblies are present or absent in GAC or local path), 
 - Any build settings living outside the repo (e.g. TeamCity settings or params) might also change without a corresponding commit.

In each case it's important to be able to distinguish one build from another (on the same or different build agents), even if the source hasn't changed. Using the build server's counter as a secondary source of version info (alongside source) makes tracing these changes, and distinguishing between them by version, possible. GitVersion's approach, unless I've misunderstood, is to use the number of commits on a branch as the source of BuildMetaData, where I would previously have used the "build counter". This makes a great deal of sense but appears to lose the build counter info.

I'm interested in the community's opinions on this. 
 - Are any of my assumptions about the significance of the build counter wrong? (This would make me happy!)
 - Is there a sane way of getting the build counter info into the "BuildMetaData" variable alongside the revision data, or would it have to be one-or-other? 
 - Is there a better approach to reflecting untracked changes (e.g. dummy commits)?
 - Is there a useful compromise by including this info (usually available as an env var) in the "FullBuildMetaData" and hence "InformationalVersion"?

**Comment by gep13** [comment]
While I see your point, I am not entirely sure I agree with it :-)

For me, any setup required to make the build happen should be done within the build script that I am using, therefore, it shouldn't matter where I am running the build, whether it be locally on my own machine, or on a build server.  As a result, the generated version number is the same for each server it runs on.

In terms of adding in the additional information, you could look to constructing the full version number using the discrete parts, which are all available as environment variables.  That would allow you to add the build counter information into the meta data as required.

**Comment by deyvsh** [comment]
Thanks for the input! 

I agree in principle about the "build script must pave its own way" policy, but we're running a company-wide "farm" of TeamCity agents so it's impossible to completely defend from the impact of other people's changes on the build server (even change control generally only allows you to unpick what went wrong after the fact). It's also not safe to assume that every team will follow the policy perfectly, and I'd like to have a "plug-and-go" versioning approach that we can use everywhere. Stupid real world! :grin: 

Thanks also for the tip about using environment vars - I'll have a play with that.

**Comment by JakeGinnivan** [comment]
Hrrmm, I thought I responded to this. 

Since teamcity 9 build configuration can be checked in, see https://confluence.jetbrains.com/display/TCD9/Storing+Project+Settings+in+Version+Control

My take on it is:

 - The CI build creates a binary, the build counter is available as a variable on the build if you need to look at it
 - The release build is from a build chain and takes the output from the CI build and publishes it, once a binary is published it is the gold thing and you shouldn't be able to republish that same version.

So I don't think in reality it should matter but if you need it feel free to submit a PR which can add extra info to the full version?

**Comment by deyvsh** [comment]
Righto, thanks. As a caveat (in case it saves someone else time) it looks like TC doesn't store alternate configs per branch.
