### ISSUE TITLE
Annotated tags and other non-merge commits in master

### ISSUE THREAD

**Issue by asbjornu** [ParticularLabs/GitVersion#434]
GitVersion seems to be pretty strict on only minting a new version on merge commits in `master`. If any other type of commits are performed in `master`, like an accidental edit in a README through the GitHub  web site or an annotated tag, GitVersion mints `0.0.0.0` as the version number.

A more correct behavior would imo be to fail, so the whole build fails, instead of producing builds that push out NuGet packages with `0.0.0.0` as the version number.

Even better would be if GitVersion was a bit more lenient in the version discovery algorithm so it allowed random commits on `master`. Thoughts?

**Comment by MeirionHughes** [comment]
In theory it shouldn't matter. As I understand it, the version number should come out as last 'tag' + "unstable-#commits" after tag. So, say you accidentally commit after 1.0 tag, the semversion will be something like 1.0.0-unstable1. If you really don't want that you could always simply more the tag further up.

**Comment by gep13** [comment]
I would have to agree with @MeirionHughes, and I am fairly sure that I have seen this happen on some of my repos as well.

@asbjornu can you confirm what version of GitVersion you are using?

**Comment by asbjornu** [comment]
I agree that it shouldn't matter, @MeirionHughes. The project in question uses version 2.0.1 of GitVersionTask, @gep13. Will upgrading to the 3.0 beta help?

**Comment by gep13** [comment]
@asbjornu in the version 3 update, which @JakeGinnivan has put a ton of work into, the strategies for detecting the next version number have been completely changed.  As a result, it is possible that it will now work as expected.  Definitely worth trying, and once 3 is released, it is unlikely any further changes will be made to the v2 release.  so worth a try.

**Comment by asbjornu** [comment]
I just upgraded to v3b2 in `develop`, merged it to `master` and tagged that merge-commit with annotation. Seems to work just fine. I'll do a bit more testing, but it seems like @JakeGinnivan's great work in v3 has paid off! :smile:

**Comment by gep13** [comment]
Sweet! :+1:

**Comment by JakeGinnivan** [comment]
Just need to finish v3 off and get stable released

**Comment by asbjornu** [comment]
@JakeGinnivan Indeed. Further testing shows that version 3 handles this much better than version 2. There are, however, a few issues I've discovered that I think needs some attention before version 3 can be considered stable. Please see #437 and #443.
