### ISSUE TITLE
What happend to GitFlowVersionTask?

### ISSUE THREAD

**Issue by babadofar** [ParticularLabs/GitVersion#435]
Hi,
We have used GitFlowVersionTask as part of our build procedure for some time now, all of a sudden the package is no longer available on nuget!? Trying to replace it with GitVersionTask, and get various errors,I will put those in a separate issue. But really, what happened? Need to have GitFlowVersionTask back on nuget, at least untill GitVersionTask functions with TeamCity..

**Comment by SimonCropp** [comment]
It got merged into http://www.nuget.org/packages/GitVersionTask/

**Comment by gep13** [comment]
@SimonCropp was the nuget package for GitFlowVersionTask unlised on nuget.org?

**Comment by SimonCropp** [comment]
@gep13  they are hidden. not unlisted. so people can still retrieve it to do a build. and it was done early last year

**Comment by SimonCropp** [comment]
we actually never even made it to a version 1.0 of GitFlowVersionTask

**Comment by gep13** [comment]
Ah, perfect.  So in the interim, @babadofar could still make use of:

http://www.nuget.org/packages/GitFlowVersionTask

Ideally though, we will hopefully get GitVersionTask working correctly, I have seen some other issues raised by @babadofar

**Comment by SimonCropp** [comment]
yeah i suspect the errors would have been cause by some intermittent nuget down time. Note to see the list http://www.nuget.org/packages/GitFlowVersionTask u will need to login

**Comment by babadofar** [comment]
OK, this is working now. Quite strange that this was the only unavailable package, but, that's life isn't it. ;)

nuget install  GitFlowVersionTask -Version 0.8.0 -NoCache
Installing 'GitFlowVersionTask 0.8.0'.
Successfully installed 'GitFlowVersionTask 0.8.0'.

**Comment by JakeGinnivan** [comment]
@babadofar can you raise the errors which prevented you from using GitFlowVersionTask?

**Comment by babadofar** [comment]
Sure, the issue is here https://github.com/ParticularLabs/GitVersion/issues/436
And it boils down to avoiding the problems stemming from libgit2sharp not supporting ssh. 
We use a "prefetch all branches" script, and need the ability to set the nofetch option on the GitVersionTask, which will be in the next release. So all in all, we're ready to upgrade to use GitVersionTask from the next stable version:)

**Comment by JakeGinnivan** [comment]
Good news :)

**Comment by gep13** [comment]
Sweet! Glad we got this sorted out :-)
