### ISSUE TITLE
Get version variables in powershell?

### ISSUE THREAD

**Issue by MeirionHughes** [ParticularLabs/GitVersion#444]
I'm in the process of moving my builds from teamcity to GitLab CI. I've opted to go the route of using  powershell calling msbuild and the project has GitVersionTask. I'm struggling to work out how to get the msbuild variables generated by GitVersionTask. Any idea?

**Comment by arthurzaczek** [comment]
I'm using the command line tool and this code snippet

    $str = GitVersion.exe | out-string
    $json = ConvertFrom-Json $str
    $version = $json.NuGetVersionV2

**Comment by gep13** [comment]
Agreed, this is a similar approach to what I have done here:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L442

Although GitVersionTask "might" create environment variables as part of it's execution, I don't think that these will be available to the calling PowerShell process.  As a result, you may have to do what is suggested here.

**Comment by MeirionHughes** [comment]
yes I think so too. GitVersionTask was easier to use when it was TeamCity, but the exe will probably be better for ps.

**Comment by gep13** [comment]
>@MeirionHughes said...
GitVersionTask was easier to use when it was TeamCity, but the exe will probably be better for ps.

That sounds appropriate to me.  :-)
