### ISSUE TITLE
Consider different naming for strategy

### ISSUE THREAD

**Issue by GeertvanHorrik** [ParticularLabs/GitVersion#446]
Continuous Delivery and Continuous Deployment are extremely confusing (at least to me). Discussed this with @JakeGinnivan , he thinks we might change this to IncrementByTag and IncrementByCommit.

What do you think?

**Comment by MeirionHughes** [comment]
Seems more intuitive, is that IncrementByTag correct though? I thought ContinuousDelivery incremented on each merge commit? 

So [IncrementBy] MergeCommitCount vs CommitCount?

**Comment by JakeGinnivan** [comment]
I agree. Here are some ideas:

 - `incrementWhen: tagged|commitAdded`
 - `uniqueVersions: true`
 - `treatCommitsAsReleases: true`
 - `mode: deployAllBuilds|releaseBuildManually` (alias for continuous deployment and delivery respectively)

Any other ideas?

**Comment by GeertvanHorrik** [comment]
I still like your first naming, which is:

mode: incrementByTag|IncrementByCommit

I would even like to vote to have the 2nd as default ;-)

**Comment by JakeGinnivan** [comment]
With the second as default, using GitHubFlow how do I do a patch release with multiple commits been merged to master?

If we can answer that question then we could look at changing default

**Comment by JakeGinnivan** [comment]
I still like the continuous deployment/delivery options. They are very descriptive of the workflow and match what each of those practices try and achieve.

With the new docs and `init` stuff do you think we could get away with leaving it.

**Comment by JakeGinnivan** [comment]
The main reason is that the reasoning for the option changes depending on what branch/part of workflow you are in. The other names are too descriptive and sometimes do not fit

**Comment by GeertvanHorrik** [comment]
Let's keep it this way. I copy the configs anyway when creating new projects so it'll work for me.
