### ISSUE TITLE
GitVersionTask should also update package.appxmanifest

### ISSUE THREAD

**Issue by onovotny** [ParticularLabs/GitVersion#449]
For projects that have a Package.appxmanifest file, it'd be great to have an option for the GitVersionTask to update the version info in it.

A couple of issues:
1. Needs to update file in-place, so probably using a regex
2. Should be an option that's off by default and opt-in via setting an msbuild property in the project file. Reason is that people may be doing their own appx versioning and the version numbers must always increase in the store.

**Comment by JakeGinnivan** [comment]
As with #450, I don't think this should be something GitVersion does. There should be another tool which takes the output of GitVersion to update different files. 

There are so many different manifests and such that it would be too many things for gitversion to do. As an example I use GitVersion to version gems, npm packages and others. We don't want GitVersion to know about all these different things.

**Comment by gep13** [comment]
I agree with this.

Assuming that the plans all come together, this could be another tool in the pipeline, along with GitReleaseNotes and GitReleaseManager, etc.
