### ISSUE TITLE
Script/Task/Command line opt for nuspecs

### ISSUE THREAD

**Issue by onovotny** [ParticularLabs/GitVersion#450]
There's not much information on how to actually update the package id in the nuspec. It's true that GitVersion sets a bunch of variables, but that leaves the end-user to create scripts for updating nuspecs.

It would be better if there was a script/msbuild task/command line option that took a specified nuspec(s) and updated the version to match the NuSpecV2 (or optionally v3) variable.

**Comment by JakeGinnivan** [comment]
I think this is the job of something else. GitVersion should give your build the variables to pass into `nuget.exe pack -version <version>`, and in your nuspec just use `$version$` in the version field.
