### ISSUE TITLE
build number not bumped when master tagged until change is pushed

### ISSUE THREAD

**Issue by richardwadsworth** [ParticularLabs/GitVersion#454]
I am getting this behaviour from TeamCity running "GitVersion 3.0.0-beta0002".

If tag HEAD of master, then push the tag and then force a build in TeamCity, I would expect the build number to reflect the new tag.  However the build major.minor.patch doesn't change until another commit is made against the repository (regardless of branch).  This means I have to commit a change to bump the build version in master which can't be right?

Steps to reproduce
```
1. master is tagged with v2.0.0
2. a commit is merged and pushed to master resulting in a build number of 2.0.0
3. master is tagged and pushed with v2.0.1
4. force a build against master in TeamCity => the resulting build number is still 2.0.0 (but I was expected 2.0.1)
5. checkout to a feature branch and commit a change and push against that branch
6. do nothing else
7. force another build against master in TeamCity => the resulting build number is now 2.0.1
```

**Comment by JakeGinnivan** [comment]
There is a rule that if a commit is tagged, it overrides other conventions. The reason is if you build and tag a commit, then rebuild it, it should not change the version which originally got built

**Comment by richardwadsworth** [comment]
I understand that rule (I think).  So my process is wrong?

So should I commit _and_ tag locally before pushing to the remote?

**Comment by JakeGinnivan** [comment]
Unsure of your process, so can't say it's wrong :)

For me tags are a record of a version, so it can be used in one or two ways:

1) Tag to create a version, I tag some commit then build it. I am creating the version for the tag so gitversion respects that tag. Once master moves on we bump patch
2) We rely on gitversion's predictive versioning, it creates the next version. When I upload the package built to nuget or release that version, I tag to record that version was released

If you let me know more about your process, I can advise you better

**Comment by JakeGinnivan** [comment]
Going to close this, would love to continue the conversation though.
