### ISSUE TITLE
Patch Version?

### ISSUE THREAD

**Issue by MeirionHughes** [ParticularLabs/GitVersion#455]
Is the Patch Count *.*.x supposed to track the number of merge commits? 

i.e. 
if I merge a branch into master I get 1.0.1, 
if I merge another branch into master I should get 1.0.2?

**Comment by JakeGinnivan** [comment]
Not by default. It should increment when you tag a release

**Comment by MeirionHughes** [comment]
Hmm odd. If I tag with release-1.0, I get 1.0. 
If I hen merge a branch I get 1.0.1+2. 
Merge another branch and I get 1.0.1+4.  

![graph](http://i60.tinypic.com/2yzlhy1.png)

**Comment by JakeGinnivan** [comment]
If a commit is tagged we take the tag version.

**Comment by MeirionHughes** [comment]
So basically any feature merged in will need to be arbitrary tagged (i.e. "some-feature"), before the patch is incremented. 

Unfortunately that this isn't the behaviour from Source-Tree; it only tags on closing release branches... each of which will override the version anyway. 

It is possible to configure the patch number to increment on each merge? Would you accept pull for the option?

**Comment by JakeGinnivan** [comment]
Yes I would accept a pull request if it did not break existing workflows

Do you have a develop branch? Source tree is using gitflow, not github flow for this.

If you are using GitHubFlow the idea is that master should be potentially shippable at any time. If you have v1.0.0 tagged on master, then it will start building 1.0.1. When you are ready to ship v1.0.1 you push to NuGet/whatever then tag that commit 1.0.1. 1.0.2 will then start building. This allows you to actually achieve SemVer as there should only be a single increment for each release when using SemVer. If it incremented each merge then you would have multiple patch increments per release, which is breaking SemVer.

**Comment by JakeGinnivan** [comment]
You can configure continuous deployment mode, then it will increment on every commit to master as well.

**Comment by MeirionHughes** [comment]
Okaydoky. Makes more sense why the tag increments like that. Not particularly intuitive at first glance. :)

**Comment by JakeGinnivan** [comment]
Suggestions welcome to improve docs/readme to help others get it :)

Sent from my Windows Phone
________________________________
