### ISSUE TITLE
Version is not incremented by commits within beta branches (release and hotfix branches)

### ISSUE THREAD

**Issue by FabianTrottmann** [ParticularLabs/GitVersion#461]
We create nuget packages with the version we got from GitVersion.exe. The problem we have, is that none of the generated versions fits our needs. We used to use LegacySemVerPadded because it is the right format to create a valid nuspec and nuget package (1.8.0-beta0001). But now we noticed, that when we create release or hotfix branches (GitFlow branching model) and create commits within these branches, the version is not incremented by commits. This leads to deployment problems, because we cannot deploy the same version (which actually is not the same version) twice.

The strange thing is, that this behavior does not appear within the develop branch (unstable). It seems that in the develop branch the SemanticVersionPreReleaseTag.Number is incremented. Where as in release and hotfix branches this number always remains one.

We could now use ClassicVersionWithTag, but then we have the problem with the format when we want to create nuget packages (1.8.0.9-beta.1 is not allowed).

**Comment by gep13** [comment]
@FabianTrottmann just wanted to check...

What version of GitVersion are you currently using?

**Comment by FabianTrottmann** [comment]
@gep13 GitVersion.Portable.2.0.1

**Comment by MeirionHughes** [comment]
try 3.0.3: choco GitVersion.Portable -pre -y

**Comment by gep13** [comment]
I would definitely suggest that you try out the current beta version, as @MeirionHughes suggests.  @JakeGinnivan has been putting in a ton of work to ensure that GitVersion is far more maintainable and support much more workflows than it did in the 2.0.x release.  It could (and hopefully will be the case) that the issue that you are seeing is already corrected.

If not, then I would suggest you raise a PR against the beta version, not directly against master.

**Comment by FabianTrottmann** [comment]
@MeirionHughes @JakeGinnivan 
The version remains the same (not incremented) as it is in 2.0.1. I'll raise a PR against the beta version.
Thanks for the quick responses

**Comment by MeirionHughes** [comment]
How about if you change the branch config to use continuous delivery? (not the one its set to by default). I think that is supposed to bump the version per commit.

**Comment by JakeGinnivan** [comment]
Yeah, try using `gitversion init` it explains the config. also read https://github.com/ParticularLabs/GitVersion/blob/master/Docs/versionIncrements.md which explains why things are like they are.

In short if we incremented every commit then you would not be doing SemVer

**Comment by JakeGinnivan** [comment]
Also see https://github.com/ParticularLabs/GitVersion/tree/master/Docs#the-semantic-version-does-not-increment-every-commit

**Comment by JakeGinnivan** [comment]
> This leads to deployment problems, because we cannot deploy the same version (which actually is not the same version) twice

If you tag each deployment with a git tag, then the version will increment as well.

**Comment by mjamin** [comment]
I think I have the same problem:

http://i.imgur.com/LSXkGOf.png

Develop might've been at 1.3.0.2-unstable before the hotfix, but once the hotfix is merged, develop is again only one commit ahead of the hotfixed master and GitVersion resets the number to 1.3.0.1-unstable. We build NuGet packages off of our develop branch (e.g. "1.3.0-unstable0001") and if the counter resets, people do not get any updates anymore.

**Comment by lassebn** [comment]
Hi, I am experiencing the same issue as @FabianTrottmann and am not quite sure what the conclusion is. Will this be fixed in a future release, so that release branches will have updated NuGet version on each commit?

**Comment by JakeGinnivan** [comment]
Great. Any thoughts on making this more discoverable/obvious?

**Comment by lassebn** [comment]
I think it is obvious enough in v3 - if you plan to make your own configuration file, I guess you would start with running GitVersion init, or running GitVersion /showconfig which gives much more usable output than the output I got from v2.

My problem was basically that I was running v2, and could not figure out what to put in the configuration file. I'm not sure about what version that documentation is referring to - might be referring to v3 features, that I then tried to use in v2?

**Comment by JakeGinnivan** [comment]
Yeah, this stuff didn't exist in v2. Doco was lagging and not clear. I hoped to have v3 out a long while ago, but live happens :P

**Comment by mattsalmon** [comment]
Hi, I'm having the same issue as the original post described, and the links referenced lead to 404 pages so I can't figure out which documentation was being cited in the answers.

In the gitflow branching model, I think there's an expectation that there may be small additional commits on the release branch before the release is finalised and the branch is closed. While it fits my expectations that the SemVer would not change, I'm not sure why the metadata element of the GitVersion output would stay forever fixed at "beta0001". 

I'm using Octopus deploy and TeamCity, and without incrementing the version metadata for additional commits, it makes it very difficult to push new packages out from the release branches because Octopus doesn't think anything has changed.

**Comment by asbjornu** [comment]
@mattsalmon: This issue was closed almost 1.5 years ago. There's not much in here of relevance anymore. I think the best thing you can do is try to find an open issue that discusses your problem, or create a new one. Continuing discussion on an issue that has been closed for so long isn't the best way forward, I think. You can always reference this issue from your new one, though.
