### ISSUE TITLE
GitVersionTask does not detect git repo if sln isn't in git root

### ISSUE THREAD

**Issue by onovotny** [ParticularLabs/GitVersion#471]
When trying to add GitVersionTask to a project in the following structure:

\\.git
\src
\src\Blah.sln
\src\SomeProject\SomeProject.csproj
\src\packages  <-- default location for packages is alongside sln

I get the following error if I turn on detailed build logging in the GitVersionTask:
```
1>MSBUILD : warning : Could not determine assembly version: Path 'C:\Users\Oren\Source\Git\MyRepo\src\' doesn't point at a valid Git repository or workdir.
1>Done executing task "WriteVersionInfoToBuildLog".
```

**Comment by Sacrelicious** [comment]
This is addressed in PR#469
